repos:
  - repo: https://github.com/rtts/djhtml
    rev: v3.0.10
    hooks:
      - id: djhtml
        files: \.html$
        exclude: ^new_env/.*\.html$  # Exclude Django's built-in templates
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
        language_version: python3
        files: \.py$
